# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
- devel
- release
warnings_are_errors: true
sudo: required

before_install:
- sudo apt-get install libmagick++-dev
- sudo apt-get install libmpfr-dev