# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
install:
- R -e "0" --args --bootstrap-packrat
- R -e "packrat::restore(restart = FALSE)"
r:
- release
- devel
warnings_are_errors: true
sudo: required
