# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: required

before_install:
- sudo apt-get install libmagick++-dev
- sudo apt-get install libmbfr-dev